[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "npm", "mariadb
"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm ci",
  "npm run build"
]

[phases.start]
cmds = [
  "php artisan optimize:clear",
  "php artisan storage:link",
  "php artisan session:table",
  "php artisan migrate --force --seed",
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]
