[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_22', 'coreutils', 'pkg-config', 'libzip', 'openssl', 'mysql80', 'git']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
